import { useEffect, useMemo, useState } from 'react';
import { Link, useBlocker } from '@tanstack/react-router';
import type { ReactNode } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, CalendarDays, ClipboardList, FileText, FlaskConical, HeartPulse, Plus, Printer, Save, Search, X, History, ArrowRight, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { AppShell } from './AppShell';
import { Toaster } from '@/components/ui/sonner';
import { meQuery, patientsQuery } from '@/lib/db';
import { clinicalQuery, fetchVersions, saveClinical } from '@/lib/clinical';
import { describeRecord, isFinal, localDay, modules, validateRecord, type ClinicalRecord } from '@/lib/clinical-model';
import type { Patient } from '@/lib/patients';

type Draft={id?:string;kind:string;patient:string;status:string;data:Record<string,string>;related:string;revision:number|null;finalized:boolean;reason:string};
const labels:Record<string,string>={dashboard:'Начало',...Object.fromEntries(Object.entries(modules).map(([key,m])=>[key,m.label]))};
const formatTime=(s:string)=>new Date(s).toLocaleString('bg-BG',{timeZone:'Europe/Sofia'});
const input='win-input w-full';
export function DoctorWorkspace({initialTab='dashboard',initialPatient='',}:{initialTab?:string;initialPatient?:string}){
 const [tab,setTab]=useState(labels[initialTab]?initialTab:'dashboard');
 const [patientId,setPatientId]=useState(initialPatient);
 const [query,setQuery]=useState('');const [status,setStatus]=useState('');
 const [day,setDay]=useState(localDay());const [week,setWeek]=useState(false);
 const [draft,setDraft]=useState<Draft|null>(null);const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<ClinicalRecord|null>(null);const [versionId,setVersionId]=useState('');const [printing,setPrinting]=useState<ClinicalRecord|null>(null);
 const qc=useQueryClient();const people=useQuery(patientsQuery);const me=useQuery(meQuery);const records=useQuery(clinicalQuery);
 const Shell=AppShell;
 useBlocker({shouldBlockFn:()=>dirty&&!window.confirm('Има незапазени промени. Да бъдат ли отхвърлени?'),enableBeforeUnload:dirty});
 const versions=useQuery({queryKey:['clinical-versions',versionId],queryFn:()=>fetchVersions(versionId),enabled:!!versionId});
 const patients=people.data??[];const all=records.data??[];
 const patient=patients.find(p=>p.dbId===patientId);
 const allowed=!!(me.data?.isAdmin||me.data?.isDoctor);
 const name=(id:string|null)=>patients.find(p=>p.dbId===id)?.fullName??'Личен запис';
 const canLeave=()=>!dirty||window.confirm('Има незапазени промени. Да бъдат ли отхвърлени?');
 useEffect(()=>{const handler=(e:Event)=>{if(dirty&&!window.confirm('Има незапазени промени. Да бъдат ли отхвърлени?'))e.preventDefault();};window.addEventListener('healthmate:before-leave',handler);return()=>window.removeEventListener('healthmate:before-leave',handler);},[dirty]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 useEffect(()=>{if(printing){document.body.classList.add('clinical-printing');const t=setTimeout(()=>window.print(),100);return()=>{clearTimeout(t);document.body.classList.remove('clinical-printing');};}return undefined;},[printing]);
 useEffect(()=>{const done=()=>setPrinting(null);window.addEventListener('afterprint',done);return()=>window.removeEventListener('afterprint',done);},[]);
 useEffect(()=>{setTab(labels[initialTab]?initialTab:'dashboard');setPatientId(initialPatient);},[initialTab,initialPatient]);
 function changeTab(key:string){if(!canLeave())return;setTab(key);setDraft(null);setDirty(false);setSelected(null);setStatus('');setQuery('');}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'open_doctor_module',description:'Open a doctor workspace module without changing medical records.',inputSchema:{type:'object',properties:{module:{type:'string',enum:Object.keys(labels)}},required:['module'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{const key=(input as {module?:string})?.module;if(!key||!labels[key])throw new Error('Непознат модул.');if(dirty)throw new Error('Първо запазете текущата форма.');changeTab(key);return {opened:key};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[dirty]);
 function create(kind=tab,related?:ClinicalRecord){if(!canLeave()||!modules[kind])return;const mod=modules[kind]!;setTab(kind);const data:Record<string,string>={};
 if(mod.fields.some(f=>f.key==='date'))data['date']=localDay();
 if(kind==='documents'){data['number']=`DOC-${crypto.randomUUID().slice(0,8).toUpperCase()}`;data['institution']='МБАЛ – Балчик';if(related){data['content']=describeRecord(related);data['type']=related.kind==='discharge'?'Епикриза':related.kind==='encounters'?'Амбулаторен лист':related.kind==='consultations'?'Консултативен лист':'Протокол от процедура';}}
 if(kind==='profile')data['name']=me.data?.full_name??'';
 if(kind==='encounters'){const pref=all.find(r=>r.kind==='profile'&&r.owner_id===me.data?.id);if(pref?.data['template'])data['history']=pref.data['template'];}
 if(kind==='discharge'&&related){data['diagnosis']=related.data['diagnosis']??'';data['icd']=related.data['icd']??'';data['history']=related.data['history']??'';}
 setDraft({kind,patient:mod.personal?'':related?.patient_id??patientId,status:mod.statuses[0]!,data,related:related?.id??'',revision:null,finalized:false,reason:''});setSelected(null);setDirty(false);
 }
 function edit(r:ClinicalRecord){if(!canLeave())return;setDraft({id:r.id,kind:r.kind,patient:r.patient_id??'',status:r.status,data:{...r.data},related:r.related_id??'',revision:r.revision,finalized:!!r.finalized_at,reason:''});setDirty(false);setSelected(null);}
 function close(){if(canLeave()){setDraft(null);setDirty(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft)return;const error=validateRecord(draft.kind,draft.data,draft.status,draft.patient,draft.related);if(error){toast.error(error);return;}
 if(draft.finalized&&!draft.reason.trim()){toast.error('Посочете причина за корекцията.');return;}
 setBusy(true);try{const title=draft.data['diagnosis']||draft.data['name']||draft.data['test']||draft.data['reason']||draft.data['title']||draft.data['number']||draft.data['specialty']||draft.data['subject']||modules[draft.kind]!.singular;
 const r=await saveClinical({...draft.id?{id:draft.id}:{},kind:draft.kind,patient_id:draft.patient||null,status:draft.status,data:draft.data,title:title.slice(0,300),related_id:draft.related||null},draft.revision,draft.reason);
 setDraft(null);setDirty(false);setSelected(r);await qc.invalidateQueries({queryKey:['clinical-records']});await qc.invalidateQueries({queryKey:['clinical-versions']});toast.success('Записано успешно');
 }catch(err){toast.error(err instanceof Error?err.message:'Записът не е успешен.');}finally{setBusy(false);}}
 const filtered=useMemo(()=>all.filter(r=>r.kind===tab&&(!patientId||r.patient_id===patientId||r.kind==='profile')&&(!status||r.status===status)&&(r.kind!=='profile'||r.owner_id===me.data?.id)&&(!query||`${r.title} ${name(r.patient_id)} ${Object.values(r.data).join(' ')}`.toLowerCase().includes(query.toLowerCase()))).filter(r=>{
 if(tab!=='appointments'||!day)return true;const start=r.data['start']?.slice(0,10)??'';const end=new Date(`${day}T12:00:00`);end.setDate(end.getDate()+(week?6:0));return start>=day&&start<=localDay(end);
 }).sort((a,b)=>tab==='appointments'?(a.data['start']??'').localeCompare(b.data['start']??''):b.updated_at.localeCompare(a.updated_at)),[all,tab,patientId,status,query,day,week,patients,me.data?.id]);
 const patientRecords=all.filter(r=>r.patient_id===patientId);
 const alerts=patientRecords.filter(r=>r.kind==='history'&&r.status==='Актуален'&&['Алергия','Алергичен статус'].includes(r.data['type']??''));
 const draftPatient=patients.find(p=>p.dbId===draft?.patient);
 const relatedOptions=all.filter(r=>r.patient_id===draft?.patient&&r.id!==draft?.id&&(['progress','discharge'].includes(draft?.kind??'')?r.kind==='admissions':draft?.kind==='administrations'?r.kind==='treatments':true));
 const totals=[{key:'appointments',label:'Часове днес',icon:CalendarDays,n:all.filter(r=>r.kind==='appointments'&&r.data['start']?.startsWith(localDay())&&!['Отменен','Неявил се'].includes(r.status)).length},{key:'admissions',label:'Активни престои',icon:HeartPulse,n:all.filter(r=>r.kind==='admissions'&&r.status==='Активна').length},{key:'tests',label:'Резултати за преглед',icon:FlaskConical,n:all.filter(r=>r.kind==='tests'&&r.status==='Потвърден резултат').length},{key:'documents',label:'Чернови на документи',icon:FileText,n:all.filter(r=>r.kind==='documents'&&r.status==='Чернова').length}];
 return <Shell title="лекарски кабинет"><Toaster position="top-center"/><div className="doctor-workspace p-4 space-y-4">
 <header className="flex flex-wrap gap-3 justify-between items-start"><div><div className="text-xs uppercase tracking-widest text-primary">МБАЛ – Балчик · Лекарски кабинет</div><h1 className="text-2xl font-semibold mt-1">{labels[tab]}</h1><p className="text-sm text-muted-foreground mt-1">{tab==='dashboard'?`Добре дошли, ${me.data?.full_name??'…'}. Вашият работен ден на едно място.`:modules[tab]?.description}</p></div>{<Link to="/patients/new" className="win-btn"><Plus className="size-4"/> Нов пациент</Link>}</header>
 <nav aria-label="Лекарски модули" className="flex flex-wrap gap-1 border-b pb-3">{Object.entries(labels).map(([key,label])=><button key={key} className={key===tab?'win-btn-primary':'win-btn'} onClick={()=>changeTab(key)}>{label}</button>)}</nav>
 <div className="panel p-3 flex flex-wrap items-center gap-3"><label className="text-sm flex-1 min-w-60">Пациент<select aria-label="Пациент" value={patientId} className={`${input} mt-1`} onChange={e=>{if(!canLeave())return;setPatientId(e.target.value);setDraft(null);setDirty(false);setSelected(null);}}><option value="">Всички мои пациенти</option>{patients.map(p=><option key={p.dbId} value={p.dbId}>{p.fullName} · {p.id}</option>)}</select></label>{patient&&<div className="text-xs"><strong>{patient.fullName}</strong><p>{patient.age} г. · {patient.id}</p><p className="text-destructive">Алергии: {patient.allergies||'Неуточнено'}{alerts.length>0&&` · ${alerts.map(r=>r.data['subject']).join('; ')}`}</p></div>}</div>
 {(people.isLoading||records.isLoading)&&<p className="flex items-center gap-2"><Loader2 className="size-4 animate-spin"/> Зареждане…</p>}
 {(people.error||records.error)&&<div role="alert" className="panel p-4 border-destructive text-destructive"><strong>Данните не са заредени.</strong><p className="mt-1">{(people.error||records.error)?.message}</p><button className="win-btn mt-2" onClick={()=>{void people.refetch();void records.refetch();}}>Опитай отново</button></div>}
 {!allowed&&me.data&&<p role="alert" className="panel p-4">Този кабинет е достъпен за потребители с роля лекар или администратор.</p>}
 {tab==='dashboard'&&<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">{totals.map(t=><button key={t.key} onClick={()=>changeTab(t.key)} className="panel p-5 text-left hover:border-primary"><t.icon className="size-5 text-primary"/><div className="text-3xl font-semibold mt-3">{records.isLoading?'…':records.error?'—':t.n}</div><p className="text-sm text-muted-foreground mt-1">{t.label}</p></button>)}</div><div className="grid lg:grid-cols-2 gap-4"><section className="panel p-4"><h2 className="font-semibold mb-3">{patient?'Хронология на пациента':'Последна активност'}</h2>{(patient?patientRecords:all).filter(r=>r.kind!=='profile').slice(0,8).map(r=><button key={r.id} onClick={()=>{changeTab(r.kind);setSelected(r);}} className="flex w-full gap-3 text-left py-3 border-b"><Activity className="size-4 text-primary mt-1"/><div className="flex-1"><p className="text-sm font-medium">{r.title}</p><p className="text-xs text-muted-foreground">{name(r.patient_id)} · {modules[r.kind]?.label} · {r.status}</p></div><span className="text-xs">{formatTime(r.updated_at)}</span></button>)}{!(patient?patientRecords:all).length&&<p className="text-sm text-muted-foreground">Още няма записи. Изберете пациент и създайте преглед или назначение.</p>}{patient?.visits.length? <div className="mt-4"><h3 className="text-sm font-semibold">Предишни прегледи</h3>{patient.visits.map((v,i)=><p key={i} className="text-sm mt-2">{v.date} · {v.diagnosis} · {v.doctor}</p>)}</div>:null}</section><section className="panel p-4"><h2 className="font-semibold mb-3">Бързи действия</h2><div className="grid grid-cols-2 gap-2">{['encounters','appointments','tests','treatments','admissions','documents'].map(key=><button disabled={!allowed||!!records.error} key={key} className="win-btn justify-between" onClick={()=>create(key)}>{modules[key]?.singular}<ArrowRight className="size-4"/></button>)}</div><h2 className="font-semibold mt-6 mb-2">Предстоящи задачи</h2>{all.filter(r=>r.kind==='tasks'&&r.status!=='Завършена').slice(0,6).map(r=><button key={r.id} className="block text-left border-b py-2 text-sm w-full" onClick={()=>{changeTab('tasks');setSelected(r);}}>{r.title}<span className="block text-xs text-muted-foreground">{r.data['due']?.replace('T',' ')||'Без срок'} · {name(r.patient_id)}</span></button>)}{!all.some(r=>r.kind==='tasks'&&r.status!=='Завършена')&&<p className="text-sm text-muted-foreground">Няма отворени задачи.</p>}</section></div></>}
 {tab!=='dashboard'&&!draft&&<><div className="flex gap-2 flex-wrap items-center"><div className="flex items-center gap-2 flex-1 min-w-48"><Search className="size-4"/><input className={input} aria-label="Търси записи" placeholder="Търсене в записите…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Статус" className="win-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Всички статуси</option>{modules[tab]?.statuses.map(s=><option key={s}>{s}</option>)}</select><button disabled={!allowed||records.isLoading||!!records.error} className="win-btn-primary" onClick={()=>create()}><Plus className="size-4"/> {modules[tab]?.singular}</button></div>
 {tab==='appointments'&&<div className="flex gap-3 items-center"><input aria-label="Ден" type="date" className="win-input" value={day} onChange={e=>setDay(e.target.value)}/><label className="text-sm"><input type="checkbox" checked={week} onChange={e=>setWeek(e.target.checked)}/> Следващи 7 дни</label></div>}
 <div className="panel overflow-auto"><table className="grid-table"><thead><tr><th>Пациент</th><th>Запис</th><th>Статус</th><th>{tab==='appointments'?'Насрочен за':'Последна промяна'}</th><th>Версия</th><th/></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{name(r.patient_id)}</td><td>{r.title}</td><td><span className="rounded bg-secondary px-2 py-1 text-xs">{r.status}</span></td><td>{tab==='appointments'?r.data['start']?.replace('T',' '):formatTime(r.updated_at)}</td><td>{r.revision}</td><td><button onClick={()=>setSelected(r)} className="win-btn">Отвори</button></td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="p-8 text-center text-muted-foreground">{records.isLoading?'Зареждане…':'Няма записи за избраните условия.'}</td></tr>}</tbody></table></div></>}
 {draft&&<form onSubmit={save} className="panel p-4 space-y-4"><div className="flex justify-between items-center"><h2 className="font-semibold">{draft.id?'Редакция':'Нов запис'} · {modules[draft.kind]?.singular}</h2><button type="button" onClick={close} className="win-btn" aria-label="Затвори"><X className="size-4"/></button></div>
 {draft.finalized&&<p className="p-3 bg-secondary text-sm">Записът е финализиран. Корекцията създава нова версия; предишната остава в историята.</p>}
 {!modules[draft.kind]?.personal&&<label className="win-label">Пациент<select required disabled={!!draft.id} className={input} value={draft.patient} onChange={e=>{setDraft({...draft,patient:e.target.value,related:''});setDirty(true);}}><option value="">Изберете пациент</option>{patients.map(p=><option key={p.dbId} value={p.dbId}>{p.fullName} · {p.id}</option>)}</select></label>}
 {draftPatient&&<div className="border-l-4 border-destructive pl-3 text-sm"><strong>{draftPatient.fullName} · {draftPatient.age} г.</strong><p>Алергии: {draftPatient.allergies||'Неуточнено'}</p>{all.filter(r=>r.patient_id===draft.patient&&r.kind==='history'&&r.status==='Актуален'&&r.data['type']==='Алергия').map(r=><p key={r.id}>{r.data['subject']} · {r.data['reaction']} · {r.data['severity']}</p>)}</div>}
 <div className="grid sm:grid-cols-2 gap-4"><label className="win-label">Статус<select className={input} value={draft.status} onChange={e=>{setDraft({...draft,status:e.target.value});setDirty(true);}}>{modules[draft.kind]?.statuses.filter(s=>!draft.finalized||isFinal(draft.kind,s)||s==='Анулиран').map(s=><option key={s}>{s}</option>)}</select></label>
 {!modules[draft.kind]?.personal&&<label className="win-label">{['progress','discharge'].includes(draft.kind)?'Свързана хоспитализация *':draft.kind==='administrations'?'Свързано назначение *':'Свързан преглед / престой / запис'}<select className={input} value={draft.related} required={['progress','discharge','administrations'].includes(draft.kind)} onChange={e=>{setDraft({...draft,related:e.target.value});setDirty(true);}}><option value="">Изберете</option>{relatedOptions.map(r=><option key={r.id} value={r.id}>{modules[r.kind]?.singular} · {r.title} · {r.created_at.slice(0,10)}</option>)}</select></label>}
 {modules[draft.kind]?.fields.map(f=><label key={f.key} className={`win-label ${f.type==='textarea'?'sm:col-span-2':''}`}>{f.label}{f.required?' *':''}{f.type==='textarea'?<textarea className={input} rows={4} maxLength={20000} value={draft.data[f.key]??''} required={f.required} onChange={e=>{setDraft({...draft,data:{...draft.data,[f.key]:e.target.value}});setDirty(true);}}/>:f.type==='select'?<select className={input} value={draft.data[f.key]??''} onChange={e=>{setDraft({...draft,data:{...draft.data,[f.key]:e.target.value}});setDirty(true);}}><option value="">Неуточнено</option>{f.options?.map(v=><option key={v}>{v}</option>)}</select>:<input className={input} type={f.type??'text'} min={f.min} max={f.max} step={f.type==='number'?'any':undefined} maxLength={2000} required={f.required} value={draft.data[f.key]??''} onChange={e=>{setDraft({...draft,data:{...draft.data,[f.key]:e.target.value}});setDirty(true);}}/>}</label>)}
 <label className="win-label sm:col-span-2">Причина за промяната {draft.finalized?'*':''}<input required={draft.finalized} className={input} value={draft.reason} onChange={e=>{setDraft({...draft,reason:e.target.value});setDirty(true);}}/></label></div>
 {draft.kind==='discharge'&&<p className="text-sm text-muted-foreground">При приключване свързаният престой се отбелязва като изписан. Проверете чакащите изследвания на пациента: {all.filter(r=>r.patient_id===draft.patient&&r.kind==='tests'&&!['Прегледан от лекар','Отменено'].includes(r.status)).length}.</p>}
 {draft.kind==='documents'&&<p className="text-xs text-muted-foreground">Финализирането пази версия в системата. То не е квалифициран електронен подпис или изпращане към НЗИС.</p>}
 <div className="flex gap-2"><button disabled={busy} className="win-btn-primary">{busy?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>} {isFinal(draft.kind,draft.status)?'Финализирай и запази':'Запази'}</button><button disabled={busy} type="button" className="win-btn" onClick={close}>Отказ</button><span aria-live="polite" className="text-xs text-muted-foreground self-center">{dirty?'Незапазени промени':''}</span></div></form>}
 {selected&&!draft&&<section className="panel p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="text-lg font-semibold">{selected.title}</h2><p className="text-sm text-muted-foreground">{name(selected.patient_id)} · {selected.status} · Версия {selected.revision}</p></div><button className="win-btn" onClick={()=>setSelected(null)} aria-label="Затвори запис"><X className="size-4"/></button></div><div className="flex gap-2 flex-wrap"><button className="win-btn" disabled={!allowed} onClick={()=>edit(selected)}>Редактирай</button><button className="win-btn" onClick={()=>setVersionId(selected.id)}><History className="size-4"/> История</button><button className="win-btn" onClick={()=>setPrinting(selected)}><Printer className="size-4"/> Печат / PDF</button>{selected.kind!=='profile'&&selected.kind!=='documents'&&<button className="win-btn" onClick={()=>create('documents',selected)}><FileText className="size-4"/> Създай документ</button>}{selected.kind==='admissions'&&selected.status!=='Изписан'&&<><button className="win-btn" onClick={()=>create('progress',selected)}>Визитация</button><button className="win-btn" onClick={()=>create('discharge',selected)}>Изписване</button></>}{selected.kind==='treatments'&&<button className="win-btn" onClick={()=>create('administrations',selected)}>Регистрирай изпълнение</button>}{selected.kind==='appointments'&&<button className="win-btn" onClick={()=>create('encounters',selected)}>Започни преглед</button>}{selected.kind==='encounters'&&<><button className="win-btn" onClick={()=>create('tests',selected)}>Назначи изследване</button><button className="win-btn" onClick={()=>create('treatments',selected)}>Назначи лечение</button></>}</div><dl className="grid sm:grid-cols-2 gap-3">{modules[selected.kind]?.fields.filter(f=>selected.data[f.key]).map(f=><div key={f.key} className={f.type==='textarea'?'sm:col-span-2':''}><dt className="text-xs text-muted-foreground">{f.label}</dt><dd className="text-sm whitespace-pre-wrap break-words mt-1">{selected.data[f.key]}</dd></div>)}</dl>{all.some(r=>r.related_id===selected.id)&&<div className="border-t pt-3"><h3 className="font-semibold text-sm">Свързани записи</h3>{all.filter(r=>r.related_id===selected.id).map(r=><button key={r.id} className="win-btn m-1" onClick={()=>{changeTab(r.kind);setSelected(r);}}>{modules[r.kind]?.label} · {r.title} · {r.status}</button>)}</div>}</section>}
 {versionId&&<section className="panel p-4"><div className="flex justify-between"><h2 className="font-semibold">История на версиите</h2><button className="win-btn" onClick={()=>setVersionId('')}>Затвори</button></div>{versions.isLoading&&<p>Зареждане…</p>}{versions.error&&<p role="alert">{versions.error.message}</p>}{versions.data?.map(v=><details key={v.revision} className="border-b py-3"><summary className="cursor-pointer text-sm">Версия {v.revision} · {formatTime(v.changed_at)} · {v.reason}</summary><p className="text-xs mt-2">Автор (ID): {v.changed_by} · {v.snapshot.status}</p><pre className="whitespace-pre-wrap font-sans text-sm mt-2">{describeRecord(v.snapshot)}</pre></details>)}</section>}
 </div>{printing&&<ClinicalPrint record={printing} patient={patients.find(p=>p.dbId===printing.patient_id)} author={me.data?.full_name??''}/>}</Shell>;
}
function ClinicalPrint({record,patient,author}:{record:ClinicalRecord;patient:Patient|undefined;author:string}){return <article className="clinical-print-sheet"><header><p>{record.data['institution']||'МБАЛ'}</p><h1>{record.kind==='documents'?record.data['type']:modules[record.kind]?.singular}</h1><p>№ {record.data['number']||record.id} · Версия {record.revision} · {record.status}</p></header>{patient&&<section><h2>Пациент</h2><p>{patient.fullName} · {patient.id}</p><p>Дата на раждане: {patient.birthDate} · ЕГН: {patient.egn}</p></section>}{modules[record.kind]?.fields.filter(f=>record.data[f.key]).map(f=><section key={f.key}><h2>{f.label}</h2><p>{record.data[f.key]}</p></section>)}<footer><p>Автор на записа (ID): {record.owner_id}</p><p>Разпечатал: {author} · {formatTime(record.updated_at)}</p><p>Подпис на лекар: ____________________</p><p>Разпечатка от вътрешната система. Не удостоверява КЕП или регистрация в НЗИС.</p></footer></article>;}

function HostedShell({children}:{children:ReactNode;title:string}){return <main className="max-w-[1500px] mx-auto">{children}</main>;}
