/** Structured doctor workspace definitions. Empty fields never imply normal findings. */
export type Field = { key: string; label: string; type?: 'textarea'|'date'|'datetime-local'|'number'|'select'|'text'; options?: string[]; required?: boolean; min?: number; max?: number };
export type Module = { label: string; singular: string; description: string; statuses: string[]; fields: Field[]; personal?: boolean };
const text = (key: string, label: string, required = false): Field => ({key,label,required});
const area = (key: string, label: string, required = false): Field => ({key,label,required,type:'textarea'});
const select = (key: string,label: string,options: string[]): Field => ({key,label,type:'select',options});
const date = (key: string,label: string): Field => ({key,label,type:'date'});
const metric = (key: string,label: string,min: number,max: number): Field => ({key,label,type:'number',min,max});
export const modules: Record<string, Module> = {
 appointments: {label:'График',singular:'Час за преглед',description:'Часове, посещения и контролни прегледи',statuses:['Записан','Пристигнал','В преглед','Приключен','Отменен','Неявил се'],fields:[{key:'start',label:'Дата и час',type:'datetime-local',required:true},metric('duration','Продължителност (минути)',5,480),select('type','Вид',['Първичен','Вторичен','Профилактичен','Консултация']),text('room','Кабинет'),area('reason','Причина за посещението',true)]},
 encounters: {label:'Прегледи',singular:'Преглед',description:'Клинична оценка и план за пациента',statuses:['Чернова','Приключен'],fields:[date('date','Дата на прегледа'),text('department','Отделение / специалност'),text('reason','Повод',true),area('complaints','Оплаквания'),area('history','Анамнеза'),area('exam','Обективно състояние'),{key:'measured',label:'Измерени на',type:'datetime-local'},metric('weight','Тегло (kg)',0.1,500),metric('height','Ръст (cm)',20,260),text('bp','Артериално налягане (mmHg)'),metric('pulse','Пулс (уд./мин)',1,300),metric('temperature','Температура (°C)',25,45),metric('respiration','Дихателна честота (/мин)',1,120),metric('spo2','SpO₂ (%)',0,100),text('diagnosis','Основна диагноза'),text('icd','МКБ-10'),select('certainty','Сигурност',['Неуточнена','Предполагаема','Потвърдена']),area('comorbidities','Придружаващи диагнози'),area('results','Прегледани резултати'),area('therapy','Терапия и назначения'),area('recommendations','Препоръки'),area('conclusion','Заключение'),date('followup','Контролен преглед')]},
 problems: {label:'Диагнози',singular:'Медицински проблем',description:'Активни и минали заболявания',statuses:['Активна','Отзвучала','В ремисия'],fields:[text('diagnosis','Диагноза',true),text('icd','МКБ-10'),date('date','Дата на установяване'),select('certainty','Сигурност',['Неуточнена','Предполагаема','Потвърдена']),select('type','Вид',['Основна','Придружаваща']),area('notes','Бележки')]},
 history: {label:'Медицинска история',singular:'Запис в историята',description:'Алергии, операции, имунизации и минали заболявания',statuses:['Актуален','Неактуален'],fields:[select('type','Категория',['Алергия','Алергичен статус','Операция','Имунизация','Минало заболяване','Фамилна анамнеза','Настойник / контакт']),text('subject','Наименование / лице',true),date('date','Дата'),select('allergy_status','Алергичен статус',['Неуточнено','Няма известни алергии','Има известни алергии']),text('reaction','Реакция'),select('severity','Тежест',['Неуточнена','Лека','Умерена','Тежка']),text('batch','Доза / партида на ваксина'),area('notes','Подробности / контакти')]},
 tests: {label:'Изследвания',singular:'Изследване',description:'Назначаване, резултати и лекарски преглед',statuses:['Назначено','В процес','Предварителен резултат','Потвърден резултат','Прегледан от лекар','Отменено'],fields:[text('test','Изследване',true),select('type','Вид',['Лабораторно','Образно','Функционално']),select('priority','Приоритет',['Планово','Бързо','Спешно']),area('question','Клиничен въпрос',true),text('diagnosis','Диагноза / МКБ-10'),text('sample','Материал / област'),{key:'collected',label:'Вземане на проба / извършване',type:'datetime-local'},text('value','Резултат / стойност'),text('unit','Единица'),text('range','Референтен интервал'),select('flag','Отклонение',['Неоценено','В интервала','Под интервала','Над интервала','Критичен резултат']),area('description','Описание / допълнителни показатели'),area('conclusion','Заключение'),text('validated_by','Валидирал специалист'),area('review','Лекарска оценка и следващо действие')]},
 treatments: {label:'Лечение',singular:'Назначение',description:'Медикаменти, процедури, режим и диета',statuses:['Активно','Спряно','Завършено'],fields:[select('type','Тип',['Лекарство','Процедура','Режим','Диета']),text('name','Наименование',true),text('form','Лекарствена форма'),text('dose','Доза'),text('unit','Мерна единица'),text('route','Път на приложение'),text('frequency','Честота / часове'),date('start','Начало'),date('end','Край'),area('instructions','Указания'),area('reason','Основание / причина за промяната')]},
 administrations: {label:'Изпълнение',singular:'Приложение / изпълнение',description:'Действително изпълнение на свързано назначение',statuses:['Изпълнено','Пропуснато','Отказано'],fields:[{key:'time',label:'Дата и час',type:'datetime-local',required:true},text('dose','Действителна доза'),text('unit','Единица'),text('route','Път на приложение'),text('performed_by','Изпълнител',true),area('reason','Причина за пропуск / бележки')]},
 admissions: {label:'Хоспитализации',singular:'Хоспитализация',description:'Прием, настаняване и болничен престой',statuses:['Активна','Преместен','Изписан'],fields:[text('number','Номер на ИЗ',true),{key:'admitted',label:'Дата и час на прием',type:'datetime-local',required:true},select('type','Прием',['Планов','Спешен']),text('department','Отделение',true),text('room','Стая'),text('bed','Легло'),text('diagnosis','Приемна диагноза',true),text('icd','МКБ-10'),area('reason','Причина за прием'),area('history','Анамнеза'),area('exam','Първоначален статус'),area('plan','Диагностичен и лечебен план'),area('transfer','Преместване — причина, отделение, приемащ лекар')]},
 progress: {label:'Визитации',singular:'Декурзус',description:'Дневни лекарски записи към болничния престой',statuses:['Чернова','Приключен'],fields:[{key:'time',label:'Дата и час',type:'datetime-local',required:true},area('complaints','Оплаквания'),area('exam','Текущо състояние',true),area('results','Нови резултати'),area('assessment','Оценка'),area('plan','План / промени в лечението')]},
 consultations: {label:'Консултации',singular:'Консултация',description:'Заявки и становища на специалисти',statuses:['Поискана','Приета','Извършена','Отменена'],fields:[text('specialty','Специалност',true),text('consultant','Консултант'),select('priority','Приоритет',['Планово','Бързо','Спешно']),area('question','Причина и въпрос',true),area('results','Предоставени резултати'),area('exam','Находка'),area('opinion','Становище'),text('diagnosis','Диагноза / МКБ-10'),area('recommendations','Препоръки')]},
 documents: {label:'Документи',singular:'Медицински документ',description:'Чернови, финализирани версии и печат',statuses:['Чернова','Финализиран','Анулиран'],fields:[select('type','Вид',['Амбулаторен лист','Консултативен лист','Епикриза','Протокол от процедура','Направление','Рецепта','Медицинско удостоверение','Информирано съгласие']),text('institution','Лечебно заведение',true),text('department','Отделение'),text('number','Номер на документа',true),date('date','Дата'),area('content','Медицинско съдържание',true),area('benefits','При съгласие: процедура, цел и ползи'),area('risks','При съгласие: рискове и алтернативи'),area('decision','При съгласие: обсъдени въпроси и решение'),area('recommendations','Препоръки / проследяване')]},
 discharge: {label:'Изписване',singular:'Епикриза',description:'Обобщение на престоя и последващи грижи',statuses:['Чернова','Приключен'],fields:[{key:'discharged',label:'Дата и час на изписване',type:'datetime-local',required:true},text('diagnosis','Окончателна диагноза',true),text('icd','МКБ-10'),area('comorbidities','Придружаващи заболявания / усложнения'),area('history','Анамнеза и състояние при прием'),area('results','Изследвания и консултации'),area('treatment','Проведено лечение и процедури'),area('course','Протичане и обсъждане'),area('condition','Състояние при изписване',true),area('home','Домашна терапия — продължава, променя се, спира се'),area('recommendations','Режим и препоръки'),area('followup','Контролни прегледи'),area('pending','Чакащи резултати и отговорен лекар')]},
 tasks: {label:'Задачи',singular:'Задача',description:'Лични задачи и проследяване',statuses:['Предстояща','В процес','Завършена'],fields:[text('title','Задача',true),{key:'due',label:'Срок',type:'datetime-local'},select('priority','Приоритет',['Нормален','Висок']),area('notes','Описание')]},
 profile: {label:'Моят профил',singular:'Настройки на лекаря',description:'Професионални данни и лични шаблони',personal:true,statuses:['Актуален'],fields:[text('name','Име',true),text('specialty','Специалност'),text('uin','Професионален идентификатор'),text('department','Отделение'),text('schedule','Работен график'),area('template','Личен шаблон за преглед — само структура, без предварителни находки')]},
};
export type ClinicalRecord = { id:string; patient_id:string|null; owner_id:string; kind:string; title:string; status:string; data:Record<string,string>; related_id:string|null; revision:number; finalized_at:string|null; created_at:string; updated_at:string };
export function validateRecord(kind:string,data:Record<string,string>,status:string,patientId:string,relatedId:string):string|null {
 const mod=modules[kind]; if(!mod) return 'Непознат модул.';
 if(!mod.personal&&!patientId) return 'Изберете пациент.';
 if(!mod.statuses.includes(status)) return 'Невалиден статус.';
 for(const f of mod.fields){ const v=(data[f.key]??'').trim(); if(f.required&&!v)return `Попълнете „${f.label}“.`; if(v&&f.type==='number'&&(!Number.isFinite(Number(v))||Number(v)<(f.min??-Infinity)||Number(v)>(f.max??Infinity)))return `Проверете „${f.label}“.`; if(v&&f.type==='select'&&!f.options?.includes(v))return `Невалидна стойност за „${f.label}“.`; }
 if(['progress','discharge','administrations'].includes(kind)&&!relatedId)return 'Изберете свързан престой или назначение.';
 if(data['start']&&data['end']&&data['end']<data['start'])return 'Краят не може да е преди началото.';
 if(kind==='encounters'&&status==='Приключен'&&(!data['diagnosis']?.trim()||!data['conclusion']?.trim()))return 'За приключване въведете диагноза и заключение.';
 if(kind==='tests'&&['Потвърден резултат','Прегледан от лекар'].includes(status)&&!data['value']?.trim()&&!data['description']?.trim())return 'Въведете резултат или описание.';
 if(kind==='tests'&&status==='Прегледан от лекар'&&!data['review']?.trim())return 'Добавете лекарска оценка.';
 if(kind==='administrations'&&status!=='Изпълнено'&&!data['reason']?.trim())return 'Посочете причина за неизпълнението.';
 return null;
}
export function isFinal(kind:string,status:string){return (['encounters','progress','discharge'].includes(kind)&&status==='Приключен')||(kind==='documents'&&status==='Финализиран');}
export function describeRecord(r:ClinicalRecord){return modules[r.kind]?.fields.filter(f=>r.data[f.key]).map(f=>`${f.label}: ${r.data[f.key]}`).join('\n\n')??'';}
export function localDay(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Sofia',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
